### ISSUE TITLE
Create new homepage that reflects our goals

### ISSUE THREAD

**Issue by heyitsolivia** [codesignlab/design-research#16]
We need a homepage that reflects the content and design based on the wirestorm we're about to do.
- include video
- include overview
- include an about section

**Comment by heyitsolivia** [comment]
Some notes taken over happy hour

![img_4108](https://cloud.githubusercontent.com/assets/1198350/9148974/fe6c46e2-3d60-11e5-9189-9af66176fc41.JPG)
![img_4109](https://cloud.githubusercontent.com/assets/1198350/9148975/01774da0-3d61-11e5-9a7c-796b1666fe24.JPG)

**Comment by heyitsolivia** [comment]
Attempt at transcribing some of these notes into action items:

**Language**
Case studies and techniques should be written about in the third person. Use they instead of we— this can help foster outside collaboration/contributions.

**Layout**
Acceptable for the homepage to have a different layout than the rest of the site. Case studies and technique pages could benefit from a sidebar that contains an index of contents.

**To Do**
- "Marker" Logo
- Color/Brand plan
- Actual wireframes
    - homepage
    - case studies index
    - techniques index (potentially same as case studies index)
- Have at least 1 case study written
- Have at least 1 technique written

**Logo**
For a mark, possibly "Design Research Is" in marker style, similar to [Allison House's](http://allison.house/) mark

**References/Tags**
Special treatment for cross referencing/linking to techniques or case studies, possibly marked with brand colors. Calls out the item similar to `code markup`.

**Color Discussion**
Potentially keeping black and white
Or keeping it light/white (light white video?) with a few accent colors


**Immediate action to be done by 8/10**
@ngrad: Write homepage copy.
@cweber: Write case study, collect media assets
@heyitsolivia: Build homepage based on sketched wireframe, determine how to create landing pages for case studies and techniques

**Comment by heyitsolivia** [comment]
See wireframe for what we need on this page. And see #21 for copy to use.

![design-research-wireframe-sketch](https://cloud.githubusercontent.com/assets/1198350/9149112/db80c818-3d67-11e5-9e4b-7ae02e85e57c.png)

**Comment by heyitsolivia** [comment]
Designing in the browser… this is banner header for the homepage so far.
157f31fe794606970dc8bd8e6377adf5c1cf4b8a

Thoughts? @cweber @ngrad
<img width="1111" alt="screen shot 2015-08-10 at 8 44 20 pm" src="https://cloud.githubusercontent.com/assets/1198350/9187629/abce16ee-3fa0-11e5-869b-3a8d73859787.png">

**Comment by cweber** [comment]
This looks good to me and in line with what we'd talked about.

I do dream of a hand written version of the name eventually (I hate seeing repeat characters), but this is good for now.
