### ISSUE TITLE
Write homepage copy based on wireframe sketch

### ISSUE THREAD

**Issue by heyitsolivia** [codesignlab/design-research#21]
We need words for the following:
- Overview mission statement
- More in-depth WTF is design research
- Why we are doing this and why design research matters

Sketch from happy hour:
![design-research-wireframe-sketch](https://cloud.githubusercontent.com/assets/1198350/9149058/ee8746b6-3d63-11e5-95e8-b2b693038935.png)

**Comment by heyitsolivia** [comment]
Define **Design Research**:

Human centered approach to solving problems

**Comment by cweber** [comment]
"Design research is a human centered design technique."

@ngrad , @heyitsolivia and I were thinking about the relationship between those terms yesterday. We kept feeling compelled to refer to the design research as human centered in some way. It gets the idea of empathy across in terms that are becoming familiar in the social good space. We had some international development folks in the workshop who were familiar with the term, etc.
