### ISSUE TITLE
Write overview for case study: OpenCongress

### ISSUE THREAD

**Issue by heyitsolivia** [codesignlab/design-research#3]
Just an introduction to design research in the OpenCongress project.

**Comment by cweber** [comment]
Open Congress, a tool that republishes and adds value to U.S. federal legislative information, had aged and become a magnificent corpse of ideas and features that needed to be rethought. The team at the Sunlight Foundation were tasked with bringing this tool back in line with the needs and interests of a newly defined user group.

To accomplish this task, the team organized and implemented a _human centered design_ process that included user interviews, affinity diagrams, 'how might we...?'s, the development of project principals, brainstorming and a set of design principles that would help produce a refined OpenCongress that would meet the needs of actual users.

**Comment by cweber** [comment]
- Our introduction to human centered design
- Preparing for user interviews
- Conducting user interviews
- Creating affinity diagrams through group bucketing activities
- Posing 'how might we...?'s
- Development of project principals
- Brainstorming and a set of design principles
- Knowledge transfer
- Belated development personas

**Comment by cweber** [comment]
Possible graphics
- Wall of stickies
- Ten principals graphic
- Element collage?

**Comment by heyitsolivia** [comment]
This is a great start. Going to close this and continue the work for this case study in #22.
