### ISSUE TITLE
Write an introduction to Design Research

### ISSUE THREAD

**Issue by heyitsolivia** [codesignlab/design-research#6]

**Comment by cweber** [comment]
What is Design research and why do it. (Brief.)
What will this site provide. (Brief.)

**Comment by cweber** [comment]
Design research is a deliberate process of asking the right people the right questions to ensure that we are creating solutions with empathy for real users.

Designresearch.is is a collection of techniques for gathering the appropriate information for a project and explores the nuances of implementing those techniques through case studies.

**Comment by heyitsolivia** [comment]
Sounds like a pretty good start, I'll close this for now.

**Comment by heyitsolivia** [comment]
Reopening this because @ngrad had some thoughts about words, I believe.
