### ISSUE TITLE
Determine vanity url for techniques and case studies

### ISSUE THREAD

**Issue by heyitsolivia** [codesignlab/design-research#9]
I'm thinking that techniques and tools can live in the root directory like so:

`designresearch.is/user-interviews`
`designresearch.is/affinity-diagrams`

while case studies could live under a subdirectory, but haven't come up with a decent name:
`designresearch.is/improving/opencongress`
`designresearch.is/in/opencongress`

Thoughts?

**Comment by cweber** [comment]
`designresearch.is/this/opencongress`

**Comment by cweber** [comment]
`designresearch.is/changing/opencongress`

**Comment by cweber** [comment]
`designresearch.is/helping/opencongress`

**Comment by heyitsolivia** [comment]
@cweber I kinda like `designresearch.is/helping/opencongress`.

`/changing` is good too, but could imply a previous state exists

what about `/making` ?

**Comment by heyitsolivia** [comment]
We settled on `/solving` after some discussion, as it alludes to the problem-solving nature of design research on a holistic scale

Some other ideas we bounced around: `/defining`, `/documenting`, `/exploring`
